"""Generate the fixture ``.kicad_mod`` footprint from a fixture + live DUT data.

One through-hole pad is stamped per included probe point at its (refreshed) DUT
coordinate, using the geometry of its assigned nail type.  The DUT board outline
is copied to ``Edge.Cuts`` and mounting holes become NPTH pads, so the generated
footprint doubles as the fixture's mechanical reference.

The pad *number* is the point ``id`` so it nets to the matching symbol pin.
"""

from __future__ import annotations

from typing import List, Tuple

from . import nail_library
from .dut_reader import DutData, OutlineShape
from .fixture_model import Fixture, SIDE_BOTTOM
from .kicad_format import (
    FOOTPRINT_VERSION, GENERATOR, GENERATOR_VERSION, font_effects, uid,
)
from .sexpr import Sym, dumps

EDGE_WIDTH = 0.1
SILK_WIDTH = 0.12


class GenerationError(Exception):
    pass


def _datum(fixture: Fixture, dut: DutData) -> Tuple[float, float]:
    if fixture.origin == "board_origin":
        return (0.0, 0.0)
    return dut.bbox_center_mm  # default: board_bbox_center


def _transform(x: float, y: float, cx: float, cy: float, side: str) -> Tuple[float, float]:
    """Map a DUT coordinate to footprint-local coords about the datum.

    Top probe side: straight translation (matches DUT top view).
    Bottom probe side: mirror about the vertical datum axis (X flips).
    """
    lx, ly = x - cx, y - cy
    if side == SIDE_BOTTOM:
        lx = -lx
    return (round(lx, 6), round(ly, 6))


def _pad_node(number: str, x: float, y: float, nail: nail_library.NailType,
              tag: str):
    attr = Sym("np_thru_hole") if not nail.plated else Sym("thru_hole")
    shape = Sym(nail.shape)
    node = [
        Sym("pad"), number if nail.plated else "", attr, shape,
        [Sym("at"), x, y],
        [Sym("size"), nail.pad_mm, nail.pad_mm],
        [Sym("drill"), nail.drill_mm],
        [Sym("layers"), "*.Cu", "*.Mask"],
    ]
    if nail.plated:
        node.append([Sym("remove_unused_layers"), False])
    node.append([Sym("uuid"), uid("pad", tag, number)])
    return node


def _outline_nodes(shapes: List[OutlineShape], cx: float, cy: float, side: str):
    nodes = []
    for i, s in enumerate(shapes):
        tag = uid("edge", str(i))
        tp = [(_transform(px, py, cx, cy, side)) for (px, py) in s.pts]
        if s.type == "segment":
            nodes.append([
                Sym("fp_line"),
                [Sym("start"), *tp[0]], [Sym("end"), *tp[1]],
                [Sym("stroke"), [Sym("width"), EDGE_WIDTH], [Sym("type"), Sym("solid")]],
                [Sym("layer"), "Edge.Cuts"], [Sym("uuid"), tag],
            ])
        elif s.type == "arc":
            nodes.append([
                Sym("fp_arc"),
                [Sym("start"), *tp[0]], [Sym("mid"), *tp[1]], [Sym("end"), *tp[2]],
                [Sym("stroke"), [Sym("width"), EDGE_WIDTH], [Sym("type"), Sym("solid")]],
                [Sym("layer"), "Edge.Cuts"], [Sym("uuid"), tag],
            ])
        elif s.type == "circle":
            cxp, cyp = tp[0]
            nodes.append([
                Sym("fp_circle"),
                [Sym("center"), cxp, cyp],
                [Sym("end"), round(cxp + s.radius_mm, 6), cyp],
                [Sym("stroke"), [Sym("width"), EDGE_WIDTH], [Sym("type"), Sym("solid")]],
                [Sym("fill"), Sym("no")],
                [Sym("layer"), "Edge.Cuts"], [Sym("uuid"), tag],
            ])
        elif s.type == "rect":
            nodes.append([
                Sym("fp_rect"),
                [Sym("start"), *tp[0]], [Sym("end"), *tp[1]],
                [Sym("stroke"), [Sym("width"), EDGE_WIDTH], [Sym("type"), Sym("solid")]],
                [Sym("fill"), Sym("no")],
                [Sym("layer"), "Edge.Cuts"], [Sym("uuid"), tag],
            ])
        elif s.type == "poly":
            pts = [Sym("pts")] + [[Sym("xy"), px, py] for (px, py) in tp]
            nodes.append([
                Sym("fp_poly"), pts,
                [Sym("stroke"), [Sym("width"), EDGE_WIDTH], [Sym("type"), Sym("solid")]],
                [Sym("fill"), Sym("no")],
                [Sym("layer"), "Edge.Cuts"], [Sym("uuid"), tag],
            ])
    return nodes


def build_footprint(fixture: Fixture, dut: DutData, name: str = "") -> str:
    """Return the ``.kicad_mod`` text for the fixture."""
    name = name or (fixture.board + " Fixture")
    cx, cy = _datum(fixture, dut)
    nails = fixture.nail_types

    fp = [
        Sym("footprint"), name,
        [Sym("version"), FOOTPRINT_VERSION],
        [Sym("generator"), GENERATOR],
        [Sym("generator_version"), GENERATOR_VERSION],
        [Sym("layer"), "F.Cu"],
        [Sym("descr"),
         f"Bed-of-nails fixture for {fixture.board} (rev {fixture.source_rev}); "
         f"probe side {fixture.probe_side}. Generated by pin_drop."],
        [Sym("attr"), Sym("through_hole")],
    ]

    # Reference + value text.
    fp.append([
        Sym("property"), "Reference", "REF**",
        [Sym("at"), 0, round(-(dut.bbox_mm[3] / 2 + 2), 3), 0],
        [Sym("layer"), "F.SilkS"], [Sym("uuid"), uid("ref", name)],
        font_effects(1.0, 0.15),
    ])
    fp.append([
        Sym("property"), "Value", name,
        [Sym("at"), 0, round(dut.bbox_mm[3] / 2 + 2, 3), 0],
        [Sym("layer"), "F.Fab"], [Sym("uuid"), uid("val", name)],
        font_effects(1.0, 0.15),
    ])

    # Probe pads.
    missing = []
    for pt in fixture.included_points():
        dp = dut.pad_by_key(pt.refdes, pt.pad)
        if dp is None:
            missing.append(pt.id)
            continue
        nail = nails.get(pt.nail) or nail_library.DEFAULT_NAILS.get(pt.nail)
        if nail is None:
            raise GenerationError(f"unknown nail type {pt.nail!r} for point {pt.id}")
        lx, ly = _transform(dp.x_mm, dp.y_mm, cx, cy, pt.side)
        fp.append(_pad_node(pt.id, lx, ly, nail, name))

    # Mounting holes from the DUT (NPTH).
    mount_nail = nails.get("mounting") or nail_library.DEFAULT_NAILS["mounting"]
    for i, hole in enumerate(dut.mounting_holes):
        lx, ly = _transform(hole.x_mm, hole.y_mm, cx, cy, fixture.probe_side)
        drill = hole.drill_mm or mount_nail.drill_mm
        pad = max(mount_nail.pad_mm, drill)   # honor the mounting nail's ring
        npth = nail_library.NailType(
            key="mounting", description="", drill_mm=drill, pad_mm=pad, plated=False)
        node = _pad_node("", lx, ly, npth, f"{name}-mh{i}")
        fp.append(node)

    # Board outline.
    fp.extend(_outline_nodes(dut.outline, cx, cy, fixture.probe_side))

    text = dumps(fp) + "\n"
    if missing:
        # Caller (plugin/CLI) surfaces this; embed a hint comment is not valid
        # s-expr, so we attach it as an attribute on the function result instead.
        build_footprint.last_missing = missing  # type: ignore[attr-defined]
    else:
        build_footprint.last_missing = []  # type: ignore[attr-defined]
    return text


def write_footprint(fixture: Fixture, dut: DutData, path: str, name: str = "") -> List[str]:
    """Write the footprint file; return the list of point ids that were missing."""
    text = build_footprint(fixture, dut, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return getattr(build_footprint, "last_missing", [])
