#!/usr/bin/env python3
"""Install the pin_drop KiCad action plugin via a loader stub.

This writes a tiny file into KiCad's plugin search path that adds this repo to
``sys.path`` and registers the plugin, so the package keeps living here and can
be updated in place (``git pull`` and "Refresh Plugins" in KiCad).

Usage:
    python3 install_plugin.py            # auto-detect newest ~/.local/share/kicad/<ver>
    python3 install_plugin.py --plugins-dir /path/to/scripting/plugins
    python3 install_plugin.py --uninstall
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

REPO = os.path.dirname(os.path.abspath(__file__))
STUB_NAME = "pin_drop_loader.py"

STUB = '''# Auto-generated by pin_drop/install_plugin.py — do not edit.
import sys
_REPO = {repo!r}
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)
# Drop any cached pin_drop modules so KiCad's "Refresh Plugins" reloads edits
# in place (Python otherwise keeps the first-imported version for the session).
for _m in [m for m in list(sys.modules) if m == "pin_drop" or m.startswith("pin_drop.")]:
    del sys.modules[_m]
from pin_drop.plugin import register_plugins
register_plugins()
'''


def default_plugins_dir() -> str:
    base = os.path.expanduser("~/.local/share/kicad")
    # macOS fallback.
    if not os.path.isdir(base):
        base = os.path.expanduser("~/Documents/KiCad")
    versions = sorted(glob.glob(os.path.join(base, "*")))
    versions = [v for v in versions if os.path.isdir(v)
                and os.path.basename(v)[0].isdigit()]
    if not versions:
        raise SystemExit(f"could not find a KiCad version dir under {base}; "
                         f"pass --plugins-dir explicitly")
    return os.path.join(versions[-1], "scripting", "plugins")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--plugins-dir", help="KiCad scripting/plugins directory")
    ap.add_argument("--uninstall", action="store_true")
    args = ap.parse_args(argv)

    plugins_dir = args.plugins_dir or default_plugins_dir()
    stub_path = os.path.join(plugins_dir, STUB_NAME)

    if args.uninstall:
        if os.path.exists(stub_path):
            os.remove(stub_path)
            print(f"removed {stub_path}")
        else:
            print("nothing to uninstall")
        return 0

    os.makedirs(plugins_dir, exist_ok=True)
    with open(stub_path, "w", encoding="utf-8") as fh:
        fh.write(STUB.format(repo=REPO))
    print(f"installed loader -> {stub_path}")
    print("In KiCad PCB Editor: Tools > External Plugins > Refresh Plugins.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
